name: Deploy Release (Weekly)

on:
  schedule:
    # Run every sunday at 16:00 UTC (6 PM CET)
    - cron: '0 16 * * 0'

jobs:
  deploy-release:
    name: Deploy Release
    uses: ./.github/workflows/deploy-release.yml
    with:
      version-name: Weekly
      release-notes: 'Weekly build of the main branch.'
      tag-name: weekly
      publish-prerelease: true
